version: 2
jobs:
  test:
    working_directory: /go/src/github.com/segmentio/terraform-provider-kubeapply
    docker:
      - image: circleci/golang:1.17
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.sum" }}-2
      - setup_remote_docker:
          reusable: true
          docker_layer_caching: true
      - run:
          name: Install deps
          command: |
            go mod vendor
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Run Snyk
          environment:
            SNYK_LEVEL: 'FLHI'
          command: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh
      - save_cache:
          key: go-modules-{{ checksum "go.sum" }}-2
          paths:
            - "/go/pkg/mod"

  publish:
    working_directory: /go/src/github.com/segmentio/terraform-provider-kubeapply
    docker:
      - image: circleci/golang:1.17

    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          docker_layer_caching: true
      - run:
          name: ECR Login
          command: |
            sudo apt-get update && sudo apt-get install --yes python3 python3-pip
            pip3 install awscli==1.16.292
            $(aws ecr get-login --no-include-email --region ${AWS_REGION} --registry-ids ${AWS_ACCOUNT_ID})
      - run:
          name: Build and push main image
          command: |
            export SHORT_GIT_SHA=$(echo ${CIRCLE_SHA1} | cut -c -7)
            docker build \
              -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/terraform-provider-kubeapply:${SHORT_GIT_SHA} \
              --build-arg VERSION_REF=${SHORT_GIT_SHA} \
              .
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/terraform-provider-kubeapply:${SHORT_GIT_SHA}

workflows:
  version: 2
  run:
    jobs:
      - test:
          context: snyk
      - publish:
          context: segmentio-org-global
          requires: [test]
          filters:
            # Never publish from a branch event
            branches:
              ignore: /.*/
            # Release only on tag push events like vX[.Y.Z...][-whatever]
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/
