apiVersion: v1
kind: Config
clusters:
- cluster:
    {{- if .CAData }}
    certificate-authority-data: {{ .CAData }}
    {{- end }}
    {{- if .Insecure }}
    insecure-skip-tls-verify: true
    {{- end }}
    {{- if .Server }}
    server: {{ .Server }}
    {{- end }}
  name: kubeapply-cluster
contexts:
- context:
  name: default-context
  context:
    cluster: kubeapply-cluster
    user: terraform-user
current-context: default-context
users:
- name: terraform-user
  user:
    {{- if .Token }}
    token: {{ .Token }}
    {{- end }}
    {{- if .ClientCertData }}
    client-certificate-data: {{ .ClientCertData }}
    {{- end }}
    {{- if .ClientKeyData }}
    client-key-data: {{ .ClientKeyData }}
    {{- end }}
    {{- if .Username }}
    username: {{ .Username }}
    {{- end }}
    {{- if .Password }}
    password: {{ .Password }}
    {{- end }}
    {{- if .Exec }}
    exec:
      apiVersion: {{ .Exec.ApiVersion }}
      command: {{ .Exec.Command }}
      {{- if .Exec.Env }}
      env:
      {{- range  $key, $value := .Exec.Env }}
      - name: "{{ $key }}"
        value: "{{ $value }}"
      {{- end }}
      {{- end }}
      {{- if .Exec.Args }}
      args:
      {{- range .Exec.Args }}
      - "{{.}}"
      {{- end }}
      {{- end }}
    {{ end }}
